[package]
name = "rust_gcode_sender"
version = "0.1.0"
authors = ["karl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3"
tui = "0.9"
termion = "1.5"
gcode = "0.6"
regex = "1"