on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install libudev
        run: sudo apt-get install libudev-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
